---
name: Test
description: Test go code

inputs:
  GO_VERSION:
    description: "go version to use for running tests"
    required: true
    default: ""

runs:
  using: "composite"
  steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.GO_VERSION }}

    - name: Update deps
      run: go mod tidy
      shell: bash

    - name: Install go test sum
      run: go install gotest.tools/gotestsum@latest
      shell: bash

    - name: Run tests
      run: gotestsum  --format testname ./... --coverprofile=cover.out -race
      shell: bash

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./cover.out
