---
name: Becnhmarks
description: "Run benchmarks"

inputs:
  GITHUB_TOKEN:
    description: "secret used for publish pages"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x

    - name: Run benchmark
      run: |
        cd benchmarks/logger/
        go test -bench . -benchmem
        go test -bench . -benchmem | tee ../../output.txt
      shell: bash

    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: Log benchmarks
        tool: 'go'
        output-file-path: output.txt
        github-token: ${{ inputs.GITHUB_TOKEN }}
        auto-push: true
        benchmark-data-dir-path: ""
