---
name: Linter
description: Lint go code

inputs: { }

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x

    - name: Run linting
      uses: golangci/golangci-lint-action@v3
