---
name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint code
        uses: ./.github/actions/lint

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run unit tests
        uses: ./.github/actions/unit-test

  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run benchmark
        uses: ./.github/actions/bench-diff
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
