---
name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  conventional-commit:
    name: Check for conventional commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check commit
        uses: damianopetrungaro/action-conventional-commits@v1.0.3

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint code
        uses: ./.github/actions/lint

  unit-test:
    strategy:
      matrix:
        go-version: [ 1.16.x, 1.17.x, 1.18.x ]

    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run unit tests
        uses: ./.github/actions/unit-test
        with:
          GO_VERSION: ${{ matrix.go-version }}


  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - conventional-commit
      - unit-test
      - lint
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fallback-version: v0.4.0
          version-file: ./.github/release/release.json

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
