---
name: Publish Benchmarks

on:
  push:
    branches:
      - main

permissions:
  deployments: write
  contents: write

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run benchmark
        uses: ./.github/actions/bench-diff
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
